# Step 1: Import Libraries and Load CSV Files

In this step, we will:

- Import the required Python libraries.
- Load the source and target medical datasets.
- Display the first few rows of each dataset.

In [20]:
# Import required libraries

import pandas as pd
import numpy as np

# Load the source and target datasets

In [21]:

source_df = pd.read_csv("medical_dataset_source_schema.csv")
target_df = pd.read_csv("medical_dataset_target_schema.csv")

# Display First Five Rows

In [22]:
print("========== SOURCE DATASET ==========\n")
display(source_df.head())

print("\n========== TARGET DATASET ==========\n")
display(target_df.head())

========== SOURCE DATASET ==========

,Record_ID,Patient Age,Sex,Blood Sugar,BP,Body Mass Index,Serum Insulin,Cholesterol Level,Smoking Status,Disease
0,10001,61,M,76,107,24.6,129,155,Smoker,Negative
1,10002,64,M,178,62,18.7,126,179,Smoker,Positive
2,10003,56,M,209,86,23.3,157,121,Smoker,Positive
3,10004,65,F,157,77,21.7,187,146,Smoker,Positive
4,10005,45,M,161,82,32.5,37,237,Smoker,Positive

========== TARGET DATASET ==========

,Patient_ID,Age,Gender,Glucose,BloodPressure,BMI,Insulin,Cholesterol,Smoker,Diagnosis
0,1,61,Male,76,107,24.6,129,155,Yes,No Diabetes
1,2,64,Male,178,62,18.7,126,179,Yes,Diabetes
2,3,56,Male,209,86,23.3,157,121,Yes,Diabetes
3,4,65,Female,157,77,21.7,187,146,Yes,Diabetes
4,5,45,Male,161,82,32.5,37,237,Yes,Diabetes

In [23]:
print("Source Dataset Shape :", source_df.shape)
print("Target Dataset Shape :", target_df.shape)

Source Dataset Shape : (2000, 10)
Target Dataset Shape : (2000, 10)

# Cell 5: Display Column Names

In [24]:
print("Source Columns:")
print(source_df.columns.tolist())

print("\nTarget Columns:")
print(target_df.columns.tolist())

Source Columns:
['Record_ID', 'Patient Age', 'Sex', 'Blood Sugar', 'BP', 'Body Mass Index', 'Serum Insulin', 'Cholesterol Level', 'Smoking Status', 'Disease']

Target Columns:
['Patient_ID', 'Age', 'Gender', 'Glucose', 'BloodPressure', 'BMI', 'Insulin', 'Cholesterol', 'Smoker', 'Diagnosis']

# Step 2: Schema Analysis

In this step, we will analyze both datasets by checking:

- Column names
- Data types
- Missing values
- Number of unique values

This information will help us understand the structure of both datasets before performing AI-based schema mapping.

In [25]:
def analyze_schema(df, dataset_name):
    """
    Analyze the schema of a dataset.

    Parameters:
        df (DataFrame): Input dataframe
        dataset_name (str): Name of the dataset
    """

    print("=" * 70)
    print(f"{dataset_name} SCHEMA ANALYSIS")
    print("=" * 70)

    schema_info = pd.DataFrame({
        "Column Name": df.columns,
        "Data Type": df.dtypes.values,
        "Missing Values": df.isnull().sum().values,
        "Unique Values": df.nunique().values
    })

    display(schema_info)

In [26]:
analyze_schema(source_df, "SOURCE DATASET")

analyze_schema(target_df, "TARGET DATASET")

======================================================================
SOURCE DATASET SCHEMA ANALYSIS
======================================================================

         Column Name Data Type  Missing Values  Unique Values
0          Record_ID     int64               0           2000
1        Patient Age     int64               0             60
2                Sex    object               0              2
3        Blood Sugar     int64               0            151
4                 BP     int64               0             51
5    Body Mass Index   float64               0            241
6      Serum Insulin     int64               0            286
7  Cholesterol Level     int64               0            181
8     Smoking Status    object               0              2
9            Disease    object               0              2

======================================================================
TARGET DATASET SCHEMA ANALYSIS
======================================================================

     Column Name Data Type  Missing Values  Unique Values
0     Patient_ID     int64               0           2000
1            Age     int64               0             60
2         Gender    object               0              2
3        Glucose     int64               0            151
4  BloodPressure     int64               0             51
5            BMI   float64               0            241
6        Insulin     int64               0            286
7    Cholesterol     int64               0            181
8         Smoker    object               0              2
9      Diagnosis    object               0              2

In [27]:
print("SOURCE DATASET INFO")
source_df.info()

print("\n" + "="*70 + "\n")

print("TARGET DATASET INFO")
target_df.info()

SOURCE DATASET INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Record_ID          2000 non-null   int64
 1   Patient Age        2000 non-null   int64
 2   Sex                2000 non-null   object
 3   Blood Sugar        2000 non-null   int64
 4   BP                 2000 non-null   int64
 5   Body Mass Index    2000 non-null   float64
 6   Serum Insulin      2000 non-null   int64
 7   Cholesterol Level  2000 non-null   int64
 8   Smoking Status     2000 non-null   object
 9   Disease            2000 non-null   object
dtypes: float64(1), int64(6), object(3)
memory usage: 156.4+ KB

======================================================================

TARGET DATASET INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Patient_ID     2000 non-null   int64
 1   Age            2000 non-null   int64
 2   Gender         2000 non-null   object
 3   Glucose        2000 non-null   int64
 4   BloodPressure  2000 non-null   int64
 5   BMI            2000 non-null   float64
 6   Insulin        2000 non-null   int64
 7   Cholesterol    2000 non-null   int64
 8   Smoker         2000 non-null   object
 9   Diagnosis      2000 non-null   object
dtypes: float64(1), int64(6), object(3)
memory usage: 156.4+ KB

# Basic Statistics (Numerical Columns)

In [28]:
print("SOURCE DATASET STATISTICS")
display(source_df.describe())

print("\nTARGET DATASET STATISTICS")
display(target_df.describe())

SOURCE DATASET STATISTICS

,Record_ID,Patient Age,Blood Sugar,BP,Body Mass Index,Serum Insulin,Cholesterol Level
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000
mean,11000.500000,49.949500,144.584000,85.052500,29.92795,157.977000,210.223500
std,577.494589,17.384449,43.276823,14.558734,6.92946,81.907136,52.010038
min,10001.000000,21.000000,70.000000,60.000000,18.00000,15.000000,120.000000
25%,10500.750000,35.000000,107.000000,73.000000,23.87500,88.000000,165.000000
50%,11000.500000,50.000000,145.000000,85.000000,30.00000,159.000000,210.000000
75%,11500.250000,65.000000,181.000000,97.000000,35.90000,230.000000,255.000000
max,12000.000000,80.000000,220.000000,110.000000,42.00000,300.000000,300.000000

TARGET DATASET STATISTICS

,Patient_ID,Age,Glucose,BloodPressure,BMI,Insulin,Cholesterol
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000
mean,1000.500000,49.949500,144.584000,85.052500,29.92795,157.977000,210.223500
std,577.494589,17.384449,43.276823,14.558734,6.92946,81.907136,52.010038
min,1.000000,21.000000,70.000000,60.000000,18.00000,15.000000,120.000000
25%,500.750000,35.000000,107.000000,73.000000,23.87500,88.000000,165.000000
50%,1000.500000,50.000000,145.000000,85.000000,30.00000,159.000000,210.000000
75%,1500.250000,65.000000,181.000000,97.000000,35.90000,230.000000,255.000000
max,2000.000000,80.000000,220.000000,110.000000,42.00000,300.000000,300.000000

# Basic Statistics (Categorical Columns)

In [29]:
print("SOURCE CATEGORICAL DATA")
display(source_df.describe(include='object'))

print("\nTARGET CATEGORICAL DATA")
display(target_df.describe(include='object'))

SOURCE CATEGORICAL DATA

         Sex Smoking Status   Disease
count   2000           2000      2000
unique     2              2         2
top        M     Non-Smoker  Positive
freq    1000           1011      1527

TARGET CATEGORICAL DATA

       Gender Smoker Diagnosis
count    2000   2000      2000
unique      2      2         2
top      Male     No  Diabetes
freq     1000   1011      1527

# Step 3: Generate Column Metadata

In this step, we will create metadata for every column in both datasets.

The metadata includes:

- Column Name
- Data Type
- Number of Missing Values
- Number of Unique Values
- Sample Values

This metadata will later be used for AI-based schema matching.

In [30]:
def generate_metadata(df):
    """
    Generate metadata for each column in a dataframe.
    """

    metadata = []

    for column in df.columns:

        metadata.append({
            "Column Name": column,
            "Data Type": str(df[column].dtype),
            "Missing Values": df[column].isnull().sum(),
            "Unique Values": df[column].nunique(),
            "Sample Values": list(df[column].dropna().unique()[:5])
        })

    metadata_df = pd.DataFrame(metadata)

    return metadata_df

In [31]:
source_metadata = generate_metadata(source_df)

target_metadata = generate_metadata(target_df)

# Display Metadata
print("SOURCE DATASET METADATA")
display(source_metadata)

print("\nTARGET DATASET METADATA")
display(target_metadata)

In [32]:

print("SOURCE DATASET METADATA")
display(source_metadata)

print("\nTARGET DATASET METADATA")
display(target_metadata)

SOURCE DATASET METADATA

,Column Name,Data Type,Missing Values,Unique Values,Sample Values
0,Record_ID,int64,0,2000,"[10001, 10002, 10003, 10004, 10005]"
1,Patient Age,int64,0,60,"[61, 64, 56, 65, 45]"
2,Sex,object,0,2,"[M, F]"
3,Blood Sugar,int64,0,151,"[76, 178, 209, 157, 161]"
4,BP,int64,0,51,"[107, 62, 86, 77, 82]"
5,Body Mass Index,float64,0,241,"[24.6, 18.7, 23.3, 21.7, 32.5]"
6,Serum Insulin,int64,0,286,"[129, 126, 157, 187, 37]"
7,Cholesterol Level,int64,0,181,"[155, 179, 121, 146, 237]"
8,Smoking Status,object,0,2,"[Smoker, Non-Smoker]"
9,Disease,object,0,2,"[Negative, Positive]"

TARGET DATASET METADATA

,Column Name,Data Type,Missing Values,Unique Values,Sample Values
0,Patient_ID,int64,0,2000,"[1, 2, 3, 4, 5]"
1,Age,int64,0,60,"[61, 64, 56, 65, 45]"
2,Gender,object,0,2,"[Male, Female]"
3,Glucose,int64,0,151,"[76, 178, 209, 157, 161]"
4,BloodPressure,int64,0,51,"[107, 62, 86, 77, 82]"
5,BMI,float64,0,241,"[24.6, 18.7, 23.3, 21.7, 32.5]"
6,Insulin,int64,0,286,"[129, 126, 157, 187, 37]"
7,Cholesterol,int64,0,181,"[155, 179, 121, 146, 237]"
8,Smoker,object,0,2,"[Yes, No]"
9,Diagnosis,object,0,2,"[No Diabetes, Diabetes]"

# Step 4: Generate Column Embeddings using Sentence Transformers

In this step, we will:

- Install and import Sentence Transformers.
- Load the pre-trained embedding model.
- Convert each column name into a numerical embedding (vector).

These embeddings will be used in the next step to calculate semantic similarity between source and target columns.

In [33]:
# pip install sentence-transformers

In [34]:
from sentence_transformers import SentenceTransformer
# Load pre-trained Sentence Transformer model

model = SentenceTransformer('all-MiniLM-L6-v2')

print("Model Loaded Successfully!")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Model Loaded Successfully!

In [35]:
source_columns = source_df.columns.tolist()
target_columns = target_df.columns.tolist()

print("Source Columns:")
print(source_columns)

print("\nTarget Columns:")
print(target_columns)

Source Columns:
['Record_ID', 'Patient Age', 'Sex', 'Blood Sugar', 'BP', 'Body Mass Index', 'Serum Insulin', 'Cholesterol Level', 'Smoking Status', 'Disease']

Target Columns:
['Patient_ID', 'Age', 'Gender', 'Glucose', 'BloodPressure', 'BMI', 'Insulin', 'Cholesterol', 'Smoker', 'Diagnosis']

In [36]:
# Generate embeddings for source and target column names

source_embeddings = model.encode(source_columns)

target_embeddings = model.encode(target_columns)

print("Source Embeddings Shape :", source_embeddings.shape)
print("Target Embeddings Shape :", target_embeddings.shape)

Source Embeddings Shape : (10, 384)
Target Embeddings Shape : (10, 384)

In [37]:
print("First Source Column :", source_columns[0])

print("\nEmbedding Vector (First 10 Values):")

print(source_embeddings[0][:10])

First Source Column : Record_ID

Embedding Vector (First 10 Values):
[-0.05189827  0.1116784  -0.06787    -0.01188526 -0.01382327  0.03944755
  0.08798206  0.03544284 -0.02777112 -0.09455601]

# Step 5: Semantic Column Matching

In this step, we will:

- Calculate cosine similarity between source and target column embeddings.
- Find the best matching target column for each source column.
- Generate a mapping table with similarity scores.

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
# Calculate cosine similarity

similarity_matrix = cosine_similarity(source_embeddings, target_embeddings)

print("Similarity Matrix Shape:", similarity_matrix.shape)

Similarity Matrix Shape: (10, 10)

# Display Similarity Matrix

In [40]:
similarity_df = pd.DataFrame(
    similarity_matrix,
    index=source_columns,
    columns=target_columns
)

display(similarity_df)

,Patient_ID,Age,Gender,Glucose,BloodPressure,BMI,Insulin,Cholesterol,Smoker,Diagnosis
Record_ID,0.598816,0.127621,0.095331,0.051587,0.083197,0.116041,0.115128,0.025053,0.074274,0.099401
Patient Age,0.590978,0.583452,0.226176,0.062734,0.257718,0.119979,0.202362,0.117531,0.146078,0.302549
Sex,0.228918,0.368365,0.560826,0.223375,0.210763,0.208113,0.216693,0.169909,0.232719,0.220999
Blood Sugar,0.110649,0.097198,0.079150,0.736078,0.391213,0.275624,0.564006,0.284115,0.068433,0.147209
BP,0.243013,0.224642,0.264621,0.053347,0.399746,0.299124,0.122161,0.285225,0.210639,0.187905
Body Mass Index,0.238050,0.090926,0.286097,0.185286,0.236696,0.549173,0.273805,0.136342,0.037647,0.119600
Serum Insulin,0.164943,0.049062,0.108790,0.521675,0.311291,0.203952,0.828517,0.226515,-0.066348,0.244603
Cholesterol Level,0.109329,0.117797,0.031294,0.132573,0.124722,0.182920,0.136309,0.830755,0.042971,0.071722
Smoking Status,0.240328,0.201410,0.086718,0.041078,0.105245,0.083728,0.014676,0.145849,0.598063,0.240356
Disease,0.378191,0.279766,0.263599,0.269865,0.265039,0.225803,0.374995,0.303556,0.178428,0.633031

In [41]:
mapping = []

for i, source_col in enumerate(source_columns):

    best_match_index = similarity_matrix[i].argmax()

    target_col = target_columns[best_match_index]

    similarity_score = similarity_matrix[i][best_match_index]

    mapping.append({
        "Source Column": source_col,
        "Target Column": target_col,
        "Similarity Score": round(similarity_score, 4)
    })

mapping_df = pd.DataFrame(mapping)

display(mapping_df)

       Source Column  Target Column  Similarity Score
0          Record_ID     Patient_ID            0.5988
1        Patient Age     Patient_ID            0.5910
2                Sex         Gender            0.5608
3        Blood Sugar        Glucose            0.7361
4                 BP  BloodPressure            0.3997
5    Body Mass Index            BMI            0.5492
6      Serum Insulin        Insulin            0.8285
7  Cholesterol Level    Cholesterol            0.8308
8     Smoking Status         Smoker            0.5981
9            Disease      Diagnosis            0.6330

In [42]:
mapping_df.to_csv("column_mapping_report.csv", index=False)

print("Mapping report saved successfully!")

Mapping report saved successfully!

# Step 6: Hybrid Schema Matching

In this step we improve the mapping algorithm by considering:

- Semantic Similarity
- Data Type Similarity
- ID Column Detection
- One-to-One Mapping

This reduces incorrect mappings and produces more reliable results.

In [43]:
def is_id_column(column_name):
    """
    Check whether a column is an ID column.
    """

    column_name = column_name.lower()

    id_keywords = [
        "id",
        "record_id",
        "patient_id",
        "emp_id",
        "employee_id",
        "customer_id"
    ]

    return any(keyword in column_name for keyword in id_keywords)

Datatype Similarity

In [44]:
def datatype_similarity(source_dtype, target_dtype):
    """
    Returns datatype similarity score.
    """

    if source_dtype == target_dtype:
        return 1.0

    return 0.0

Hybrid Score Function
similarity = 80 percent remains

In [46]:
def hybrid_similarity(
    semantic_score,
    source_col,
    target_col,
    source_dtype,
    target_dtype
):
    """
    Calculate final hybrid similarity score.
    """

    final_score = semantic_score * 0.80

    # Datatype bonus
    final_score += datatype_similarity(source_dtype, target_dtype) * 0.20

    # ID Rule
    source_is_id = is_id_column(source_col)
    target_is_id = is_id_column(target_col)

    if source_is_id != target_is_id:
        final_score = 0

    return final_score

In [47]:
# Generate Hybrid Similarity Matrix
hybrid_matrix = similarity_matrix.copy()

for i, source_col in enumerate(source_columns):

    for j, target_col in enumerate(target_columns):

        hybrid_matrix[i][j] = hybrid_similarity(

            semantic_score=similarity_matrix[i][j],

            source_col=source_col,

            target_col=target_col,

            source_dtype=str(source_df[source_col].dtype),

            target_dtype=str(target_df[target_col].dtype)
        )

In [48]:
hybrid_similarity_df = pd.DataFrame(

    hybrid_matrix,

    index=source_columns,

    columns=target_columns
)

display(hybrid_similarity_df)

,Patient_ID,Age,Gender,Glucose,BloodPressure,BMI,Insulin,Cholesterol,Smoker,Diagnosis
Record_ID,0.679053,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Patient Age,0.000000,0.666762,0.180941,0.250187,0.406175,0.095983,0.361889,0.294025,0.116863,0.242039
Sex,0.000000,0.294692,0.648660,0.178700,0.168611,0.166491,0.173354,0.135927,0.386175,0.376799
Blood Sugar,0.000000,0.277758,0.063320,0.788862,0.512970,0.220499,0.651205,0.427292,0.054746,0.117767
BP,0.000000,0.379713,0.211697,0.242678,0.519797,0.239300,0.297729,0.428180,0.168511,0.150324
Body Mass Index,0.000000,0.072741,0.228878,0.148229,0.189357,0.639339,0.219044,0.109073,0.030117,0.095680
Serum Insulin,0.000000,0.239249,0.087032,0.617340,0.449033,0.163162,0.862814,0.381212,-0.053079,0.195683
Cholesterol Level,0.000000,0.294237,0.025036,0.306058,0.299778,0.146336,0.309047,0.864604,0.034377,0.057377
Smoking Status,0.000000,0.161128,0.269374,0.032863,0.084196,0.066983,0.011741,0.116679,0.678450,0.392285
Disease,0.000000,0.223813,0.410879,0.215892,0.212031,0.180642,0.299996,0.242845,0.342742,0.706425

Generate Final Mapping (One-to-One)

In [49]:
mapping = []

used_targets = set()

for i, source_col in enumerate(source_columns):

    scores = hybrid_matrix[i].copy()

    while True:

        best_idx = scores.argmax()

        target_col = target_columns[best_idx]

        score = scores[best_idx]

        if target_col not in used_targets:

            used_targets.add(target_col)

            mapping.append({

                "Source Column": source_col,

                "Target Column": target_col,

                "Similarity Score": round(score,4)

            })

            break

        else:

            scores[best_idx] = -1

In [50]:
mapping_df = pd.DataFrame(mapping)

display(mapping_df)

       Source Column  Target Column  Similarity Score
0          Record_ID     Patient_ID            0.6791
1        Patient Age            Age            0.6668
2                Sex         Gender            0.6487
3        Blood Sugar        Glucose            0.7889
4                 BP  BloodPressure            0.5198
5    Body Mass Index            BMI            0.6393
6      Serum Insulin        Insulin            0.8628
7  Cholesterol Level    Cholesterol            0.8646
8     Smoking Status         Smoker            0.6785
9            Disease      Diagnosis            0.7064

# Step 7: Medical Synonym Matching

In this step, we improve schema matching by adding a medical synonym dictionary.

Examples:
- Blood Sugar → Glucose
- BP → BloodPressure
- Sex → Gender
- Disease → Diagnosis

If two columns are known medical synonyms, their similarity score will be increased automatically.

In [51]:
medical_synonyms = {

    "blood sugar": ["glucose", "blood_glucose"],

    "bp": ["bloodpressure", "blood_pressure"],

    "sex": ["gender"],

    "body mass index": ["bmi"],

    "disease": ["diagnosis"],

    "patient age": ["age"],

    "cholesterol level": ["cholesterol"],

    "serum insulin": ["insulin"],

    "record_id": ["patient_id"]
}

In [52]:
# Synonym Matching Function
def synonym_similarity(source_col, target_col):
    """
    Returns 1 if source and target are medical synonyms.
    Otherwise returns 0.
    """

    source = source_col.lower().strip()
    target = target_col.lower().strip()

    # Exact match
    if source == target:
        return 1

    # Dictionary lookup
    if source in medical_synonyms:
        if target in medical_synonyms[source]:
            return 1

    return 0

# Update Hybrid Similarity Function

In [53]:
def hybrid_similarity(
    semantic_score,
    source_col,
    target_col,
    source_dtype,
    target_dtype
):

    score = semantic_score * 0.70

    # Datatype Bonus
    score += datatype_similarity(source_dtype, target_dtype) * 0.20

    # Synonym Bonus
    score += synonym_similarity(source_col, target_col) * 0.10

    # ID Rule
    source_is_id = is_id_column(source_col)
    target_is_id = is_id_column(target_col)

    if source_is_id != target_is_id:
        return 0

    return score

In [54]:
# regenrate hybrid matrix 
hybrid_matrix = similarity_matrix.copy()

for i, source_col in enumerate(source_columns):

    for j, target_col in enumerate(target_columns):

        hybrid_matrix[i][j] = hybrid_similarity(
            semantic_score=similarity_matrix[i][j],
            source_col=source_col,
            target_col=target_col,
            source_dtype=str(source_df[source_col].dtype),
            target_dtype=str(target_df[target_col].dtype)
        )

# generate final mapping  again

In [55]:
mapping = []

used_targets = set()

for i, source_col in enumerate(source_columns):

    scores = hybrid_matrix[i].copy()

    while True:

        best_index = scores.argmax()

        target_col = target_columns[best_index]

        score = scores[best_index]

        if target_col not in used_targets:

            used_targets.add(target_col)

            mapping.append({
                "Source Column": source_col,
                "Target Column": target_col,
                "Similarity Score": round(score, 4)
            })

            break

        scores[best_index] = -1

mapping_df = pd.DataFrame(mapping)

display(mapping_df)

       Source Column  Target Column  Similarity Score
0          Record_ID     Patient_ID            0.7192
1        Patient Age            Age            0.7084
2                Sex         Gender            0.6926
3        Blood Sugar        Glucose            0.8153
4                 BP  BloodPressure            0.5798
5    Body Mass Index            BMI            0.6844
6      Serum Insulin        Insulin            0.8800
7  Cholesterol Level    Cholesterol            0.8815
8     Smoking Status         Smoker            0.6186
9            Disease      Diagnosis            0.7431

# Step 8: Multi-Level Matching Engine

In this step, we combine multiple matching techniques:

1. Exact Match
2. Medical Synonym Match
3. Fuzzy String Matching
4. Semantic Similarity
5. Data Type Validation

This produces a more accurate final mapping score.

In [56]:
! pip install -q rapidfuzz

In [57]:
from rapidfuzz import fuzz

def exact_match(source_col, target_col):
    """
    Returns 1 if both column names are exactly the same.
    """

    return source_col.lower().strip() == target_col.lower().strip()

In [59]:
# fuzzt similarity
def fuzzy_similarity(source_col, target_col):
    """
    Calculate fuzzy similarity between two column names.
    """

    score = fuzz.token_sort_ratio(source_col, target_col)

    return score / 100

# improve hybrid score

In [60]:
def hybrid_similarity(
    semantic_score,
    source_col,
    target_col,
    source_dtype,
    target_dtype
):
    """
    Multi-Level Matching Score
    """

    # Rule 1: ID columns
    if is_id_column(source_col) != is_id_column(target_col):
        return 0

    # Rule 2: Exact Match
    if exact_match(source_col, target_col):
        return 1.0

    # Rule 3: Semantic Score
    score = semantic_score

    # Rule 4: Datatype Bonus
    if datatype_similarity(source_dtype, target_dtype):
        score += 0.10

    # Rule 5: Synonym Bonus
    if synonym_similarity(source_col, target_col):
        score += 0.15

    # Rule 6: Fuzzy Bonus
    fuzzy_score = fuzzy_similarity(source_col, target_col)

    if fuzzy_score >= 0.80:
        score += 0.10
    elif fuzzy_score >= 0.60:
        score += 0.05

    # Final score cannot exceed 1
    score = min(score, 1.0)

    return round(score, 4)

# regenrate hybrid matrix

In [62]:
hybrid_matrix = similarity_matrix.copy()

for i, source_col in enumerate(source_columns):

    for j, target_col in enumerate(target_columns):

        hybrid_matrix[i][j] = hybrid_similarity(
            semantic_score=similarity_matrix[i][j],
            source_col=source_col,
            target_col=target_col,
            source_dtype=str(source_df[source_col].dtype),
            target_dtype=str(target_df[target_col].dtype)
        )

In [63]:
# generate mapping
mapping = []
used_targets = set()

for i, source_col in enumerate(source_columns):

    scores = hybrid_matrix[i].copy()

    while True:

        best_index = scores.argmax()

        target_col = target_columns[best_index]

        if target_col not in used_targets:

            mapping.append({
                "Source Column": source_col,
                "Target Column": target_col,
                "Similarity Score": round(scores[best_index], 4)
            })

            used_targets.add(target_col)
            break

        scores[best_index] = -1

mapping_df = pd.DataFrame(mapping)

display(mapping_df)

       Source Column  Target Column  Similarity Score
0          Record_ID     Patient_ID            0.8488
1        Patient Age            Age            0.8335
2                Sex         Gender            0.8108
3        Blood Sugar        Glucose            0.9861
4                 BP  BloodPressure            0.6497
5    Body Mass Index            BMI            0.7992
6      Serum Insulin        Insulin            1.0000
7  Cholesterol Level    Cholesterol            1.0000
8     Smoking Status         Smoker            0.6981
9            Disease      Diagnosis            0.8830

# Step 9: Transform Source Dataset

In this step, we will use the generated column mapping to rename and
rearrange the source dataset according to the target schema.

In [64]:
# Create a dictionary from mapping_df

column_mapping = dict(
    zip(
        mapping_df["Source Column"],
        mapping_df["Target Column"]
    )
)

print(column_mapping)

{'Record_ID': 'Patient_ID', 'Patient Age': 'Age', 'Sex': 'Gender', 'Blood Sugar': 'Glucose', 'BP': 'BloodPressure', 'Body Mass Index': 'BMI', 'Serum Insulin': 'Insulin', 'Cholesterol Level': 'Cholesterol', 'Smoking Status': 'Smoker', 'Disease': 'Diagnosis'}

# Rename Columns and Reorder Columns

In [65]:
# Rename source columns

transformed_df = source_df.rename(columns=column_mapping)

display(transformed_df.head())

,Patient_ID,Age,Gender,Glucose,BloodPressure,BMI,Insulin,Cholesterol,Smoker,Diagnosis
0,10001,61,M,76,107,24.6,129,155,Smoker,Negative
1,10002,64,M,178,62,18.7,126,179,Smoker,Positive
2,10003,56,M,209,86,23.3,157,121,Smoker,Positive
3,10004,65,F,157,77,21.7,187,146,Smoker,Positive
4,10005,45,M,161,82,32.5,37,237,Smoker,Positive

In [66]:
# Arrange columns according to target dataset

transformed_df = transformed_df[target_df.columns]

display(transformed_df.head())

,Patient_ID,Age,Gender,Glucose,BloodPressure,BMI,Insulin,Cholesterol,Smoker,Diagnosis
0,10001,61,M,76,107,24.6,129,155,Smoker,Negative
1,10002,64,M,178,62,18.7,126,179,Smoker,Positive
2,10003,56,M,209,86,23.3,157,121,Smoker,Positive
3,10004,65,F,157,77,21.7,187,146,Smoker,Positive
4,10005,45,M,161,82,32.5,37,237,Smoker,Positive

# Check Output Schema

In [67]:
print("Target Columns")
print(target_df.columns.tolist())

print()

print("Transformed Columns")
print(transformed_df.columns.tolist())

Target Columns
['Patient_ID', 'Age', 'Gender', 'Glucose', 'BloodPressure', 'BMI', 'Insulin', 'Cholesterol', 'Smoker', 'Diagnosis']

Transformed Columns
['Patient_ID', 'Age', 'Gender', 'Glucose', 'BloodPressure', 'BMI', 'Insulin', 'Cholesterol', 'Smoker', 'Diagnosis']

# save conveted dataset

In [68]:
transformed_df.to_csv(
    "converted_medical_dataset.csv",
    index=False
)

print("Converted dataset saved successfully.")

Converted dataset saved successfully.

# Step 10: Data Standardization

In this step, we standardize the values in the transformed dataset.

Examples:
- M → Male
- F → Female
- Yes → 1
- No → 0

This ensures that the converted dataset follows the target schema consistently.

In [69]:
# Dictionary for standardizing values

standardization_rules = {

    "Gender": {
        "M": "Male",
        "F": "Female",
        "Male": "Male",
        "Female": "Female"
    },

    "Smoker": {
        "Yes": 1,
        "No": 0,
        "Y": 1,
        "N": 0
    }

}

In [70]:
# apply standization 
# Apply value standardization

for column, mapping in standardization_rules.items():

    if column in transformed_df.columns:

        transformed_df[column] = transformed_df[column].replace(mapping)

print("Data Standardization Completed Successfully!")

Data Standardization Completed Successfully!

In [71]:
# verify results
# Check unique values after standardization

for column in standardization_rules.keys():

    if column in transformed_df.columns:

        print(f"\n{column}")

        print(transformed_df[column].unique())

Gender
['Male' 'Female']

Smoker
['Smoker' 'Non-Smoker']

In [72]:
# save updatted data
transformed_df.to_csv(
    "standardized_medical_dataset.csv",
    index=False
)

print("Standardized dataset saved successfully!")

Standardized dataset saved successfully!

# Step 11: Validate the Converted Dataset

This step validates the transformed dataset by checking:

- Column names
- Column order
- Data types
- Missing values

The validation ensures that the converted dataset follows the target schema.

In [73]:
print("Checking Column Names...\n")

if list(transformed_df.columns) == list(target_df.columns):
    print("✅ Column names match the target schema.")
else:
    print("❌ Column names do not match the target schema.")

Checking Column Names...

✅ Column names match the target schema.

In [74]:
# validate data types 
validation_df = pd.DataFrame({
    "Column": target_df.columns,
    "Target Data Type": target_df.dtypes.values,
    "Converted Data Type": transformed_df.dtypes.values
})

validation_df["Match"] = (
    validation_df["Target Data Type"].astype(str)
    ==
    validation_df["Converted Data Type"].astype(str)
)

display(validation_df)

          Column Target Data Type Converted Data Type  Match
0     Patient_ID            int64               int64   True
1            Age            int64               int64   True
2         Gender           object              object   True
3        Glucose            int64               int64   True
4  BloodPressure            int64               int64   True
5            BMI          float64             float64   True
6        Insulin            int64               int64   True
7    Cholesterol            int64               int64   True
8         Smoker           object              object   True
9      Diagnosis           object              object   True

In [75]:
missing_report = pd.DataFrame({
    "Column": transformed_df.columns,
    "Missing Values": transformed_df.isnull().sum().values
})

display(missing_report)

          Column  Missing Values
0     Patient_ID               0
1            Age               0
2         Gender               0
3        Glucose               0
4  BloodPressure               0
5            BMI               0
6        Insulin               0
7    Cholesterol               0
8         Smoker               0
9      Diagnosis               0

# data summary

In [76]:
print("="*50)
print("FINAL DATASET SUMMARY")
print("="*50)

print(f"Rows    : {transformed_df.shape[0]}")
print(f"Columns : {transformed_df.shape[1]}")
print(f"Missing Values : {transformed_df.isnull().sum().sum()}")

print("\nValidation Completed Successfully!")

==================================================
FINAL DATASET SUMMARY
==================================================
Rows    : 2000
Columns : 10
Missing Values : 0

Validation Completed Successfully!

In [77]:
transformed_df.to_csv(
    "Final_Medical_Dataset.csv",
    index=False
)

print("✅ Final dataset saved successfully.")

✅ Final dataset saved successfully.